import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import tailwindcss from '@tailwindcss/vite';
import { TanStackRouterVite } from '@tanstack/router-plugin/vite';

export default defineConfig({
  plugins: [
    TanStackRouterVite({
      target: 'react',
      autoCodeSplitting: true,
      // Let tsc see the generated module augmentation so `createFileRoute('/x')`
      // and `<Link to="/x">` resolve to the real path union. Default header
      // includes `@ts-nocheck` which silently discards the augmentation.
      routeTreeFileHeader: [
        '/* eslint-disable */',
        '// noinspection JSUnusedGlobalSymbols',
        '// This file was automatically generated by TanStack Router.',
        '// You should NOT make any changes in this file as it will be overwritten.',
      ],
    }),
    react(),
    tailwindcss(),
  ],
  server: {
    port: 5173,
    host: true,
  },
});
