import { defineConfig, loadEnv, type Plugin } from 'vite';
import react from '@vitejs/plugin-react';
import tailwindcss from '@tailwindcss/vite';
import { TanStackRouterVite } from '@tanstack/router-plugin/vite';

/**
 * Injects Content-Security-Policy, X-Frame-Options, and Referrer-Policy
 * response headers on the Vite dev and preview servers.
 *
 * PRODUCTION NOTE: These headers MUST also be set at the edge/CDN layer.
 * A <meta> CSP cannot enforce frame-ancestors (clickjacking protection) —
 * only an HTTP header can. Mirror this configuration in your CDN/nginx config
 * using the VITE_API_URL environment variable for the connect-src origin.
 */
function securityHeadersPlugin(apiUrl: string, isDev: boolean): Plugin {
  // In dev, Vite HMR requires ws:/wss: for the WebSocket connection.
  const connectSrc = isDev
    ? `'self' ${apiUrl} ws: wss:`
    : `'self' ${apiUrl}`;

  // In dev allow unsafe-inline for HMR-injected scripts/styles; tighten for preview.
  const scriptSrc = isDev ? `'self' 'unsafe-inline'` : `'self'`;
  const styleSrc = `'self' 'unsafe-inline' https://fonts.googleapis.com`;

  const csp = [
    `default-src 'self'`,
    `connect-src ${connectSrc}`,
    `script-src ${scriptSrc}`,
    `style-src ${styleSrc}`,
    `font-src 'self' https:`,
    `img-src 'self' data: blob:`,
    `object-src 'none'`,
    `base-uri 'self'`,
    // frame-ancestors is intentionally omitted from the <meta> fallback in
    // index.html (browsers ignore it there). It is ONLY effective as an HTTP header.
    `frame-ancestors 'none'`,
  ].join('; ');

  const headers: Record<string, string> = {
    'Content-Security-Policy': csp,
    'X-Frame-Options': 'DENY',
    'Referrer-Policy': 'strict-origin-when-cross-origin',
  };

  function applyHeaders(server: import('vite').PreviewServer | import('vite').ViteDevServer) {
    server.middlewares.use((_req, res, next) => {
      for (const [name, value] of Object.entries(headers)) {
        res.setHeader(name, value);
      }
      next();
    });
  }

  return {
    name: 'security-headers',
    configureServer: applyHeaders,
    configurePreviewServer: applyHeaders,
  };
}

export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, process.cwd(), '');
  const apiUrl = env['VITE_API_URL'] ?? 'http://localhost:3000';
  const isDev = mode === 'development';

  return {
    plugins: [
      TanStackRouterVite({
        target: 'react',
        autoCodeSplitting: true,
        // Let tsc see the generated module augmentation so `createFileRoute('/x')`
        // and `<Link to="/x">` resolve to the real path union. Default header
        // includes `@ts-nocheck` which silently discards the augmentation.
        routeTreeFileHeader: [
          '/* eslint-disable */',
          '// noinspection JSUnusedGlobalSymbols',
          '// This file was automatically generated by TanStack Router.',
          '// You should NOT make any changes in this file as it will be overwritten.',
        ],
      }),
      react(),
      tailwindcss(),
      securityHeadersPlugin(apiUrl, isDev),
    ],
    server: {
      port: 5173,
      host: true,
    },
  };
});
